"""empty message

Revision ID: 2dbe78a7948b
Revises: c39780eb7def
Create Date: 2016-10-08 21:05:10.995077

"""

# revision identifiers, used by Alembic.
revision = '2dbe78a7948b'
down_revision = 'c39780eb7def'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('label', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'label')
    ### end Alembic commands ###
