"""empty message

Revision ID: 481d9eabc6e7
Revises: 2dbe78a7948b
Create Date: 2016-10-08 21:18:30.878842

"""

# revision identifiers, used by Alembic.
revision = '481d9eabc6e7'
down_revision = '2dbe78a7948b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_label'), 'comments', ['label'], unique=False)
    op.create_index(op.f('ix_comments_time'), 'comments', ['time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_time'), table_name='comments')
    op.drop_index(op.f('ix_comments_label'), table_name='comments')
    ### end Alembic commands ###
